### ISSUE TITLE
Setting the type of worker [question]

### ISSUE THREAD

**Issue by pjmagee** [tiangolo/meinheld-gunicorn-docker#1]
Is the type of worker still configurable in the python config file after starting it like this in the entrypoint.sh file?

https://github.com/tiangolo/meinheld-gunicorn-docker/blob/master/python3.7/entrypoint.sh#L23

**Comment by tiangolo** [comment]
The type of worker in this image is Meinheld (at least by default) which is what provides all the performance benefits.

**Comment by pjmagee** [comment]
I can close this. Thanks

**Comment by tiangolo** [comment]
Thanks for coming back and closing it.
