### ISSUE TITLE
Allow use of additional gunicorn options

### ISSUE THREAD

**Issue by muuvmuuv** [tiangolo/meinheld-gunicorn-docker#10]
I would like to use `--reload` in my local env, so I do not need to restart the hole server again. Allow passing additional arguments would solve this and also allow settings SSL options e.g.

**Comment by duusty** [comment]
+1

**Comment by iehoshia** [comment]
+1

**Comment by muuvmuuv** [comment]
The recommended way of saying "I want this feature as well" is by "thumb up" the original comment. The reason is, that GitHub provides filtering for issues and if all are doing "+1" this issue would never list before others and does not get prioritized. Just a little side note 😊.

@duusty @iehoshia

**Comment by stanislav-zaprudskiy** [comment]
Recent versions of gunicorn (19.7+) support [`GUNICORN_CMD_ARGS`](https://docs.gunicorn.org/en/stable/settings.html#settings) environment variable, which could be used to pass additional options as command line arguments.

**Comment by TMiguelT** [comment]
Also, these images support a [custom config file](https://github.com/tiangolo/meinheld-gunicorn-docker#gunicorn_conf) which is the simplest and most powerful way to set any of these options.

**Comment by tiangolo** [comment]
Thanks for the help here everyone! 👏  🙇 

If that solves the original problem, then you can close this issue @muuvmuuv  ✔️

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
