### ISSUE TITLE
HowTo migrate from gunicorn to meinheld-gunicorn-docker

### ISSUE THREAD

**Issue by iehoshia** [tiangolo/meinheld-gunicorn-docker#11]
Hi,

I would be great to have docs about how to migrate from gunicorn (systemd, supervisor) to meinheld-gunicorn-docker. Also, how to work with virtualenv too.

**Comment by tiangolo** [comment]
If your code has the same structure it should be a matter of just changing the `Dockerfile`. In the other image you shouldn't have to deal with Supervisor, as the image does the work for you.

In this image, there is no need for Supervisor as everything is managed by Gunicorn, so, again, there's nothing you should have to change.

None of the images use Systemd internally.

Virtual environments are actually related to Python itself, not to this image, but here's a good article you can read: https://snarky.ca/a-quick-and-dirty-guide-on-how-to-install-packages-for-python/
