### ISSUE TITLE
pyodbc in meinheld-gunicorn:python3.6

### ISSUE THREAD

**Issue by betizad** [tiangolo/meinheld-gunicorn-docker#12]
Hello,

I have been using meinheld-gunicorn:python3.6 for quite a year now and it had been working quite well to host a dash/plotly app in a docker image. In a recent feature update I need to add pyodbc library but the pip installation fails during the  build process. AFter some searching I realized that this is due to the depenency to libc-dev unixodbc-dev packages. I tried to add the following line:

`RUN apk add --no-cache gcc g++ libc-dev unixodbc-dev
`
but I get the error that the command apk can not be found. Do you have any suggestion on how to resolve this? Or do you suggest another docker build to use?

I have the following requirements.txt file 

```
pyodbc==4.0.27
dash==1.4.1
plotly==4.2.0
dash-daq==0.2.1
azure-storage-blob==2.1.0
flask-caching==1.7.1
pillow==6.2.0
numpy==1.16.2
pandas==0.24.2
```

and my docker file is as follows:

```
FROM tiangolo/meinheld-gunicorn:python3.6
WORKDIR /app
ADD requirements.txt /app/
RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org -U pip
RUN pip install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade -r requirements.txt

ADD . /app/
ENV WEB_CONCURRENCY 1
ENV LOG_LEVEL debug
```

**Comment by tiangolo** [comment]
`apk` is a command for Alpine images. You are using the default image based on Debian, so it should be even easier.

But it would would be with something like:

```Dockerfile

RUN apt-get install -y libc-dev unixodbc-dev
```

Or something like that. :warning: Warning: I didn't test that, it's just an example of how it might be.

To be sure, you have to check what are the dependencies for `pyodbc` for Debian and how to install them in their official docs.
