### ISSUE TITLE
How to adapt for Django

### ISSUE THREAD

**Issue by adaminfinitum** [tiangolo/meinheld-gunicorn-docker#13]
I'm trying to get a Django instance up and running on Google Cloud Run using this image as a base but I'm a not sure how exactly to customize it.

Let's say my Django instance is named `foo`.

Inside Docker it is called in the directory `/app`

So if I understand this correctly, my WSGI application lives at `/app/foo/foo/wsgi.py` whereas in this project it lives in `/app/app/main.py`

Would I just copy the contents of `/app/foo/foo/wsgi.py` to `/app/app/main.py`?

My WSGI application is literally named `application`, whereas this one expects `app` ... can I just add a variable assignment of `app = application` to handle this?

**Comment by tiangolo** [comment]
Yeah, check the configs in the docs: https://github.com/tiangolo/meinheld-gunicorn-docker#environment-variables

**Comment by tiangolo** [comment]
Someone was asking on another channel about this issue, so here are a bit more details:

It would probably be something like `MODULE_NAME=foo.foo.wsgi`, that points to the file `foo/foo/wsgi.py` and `VARIABLE_NAME=application` that would point to a variable named `application` inside of the file `wsgi.py`.
