### ISSUE TITLE
Compatible with nginx-proxy ?

### ISSUE THREAD

**Issue by pupattan** [tiangolo/meinheld-gunicorn-docker#18]
Hi,
I am already using nginx-proxy https://github.com/nginx-proxy/nginx-proxy for multiple containers with uwsgi-nginx-docker (Django)
I want to update them using meinheld-gunicorn-docker.
Is it possible ? how can i use meinheld-gunicorn-docker with nginx-proxy ?
Any other suggestion ?

**Comment by tiangolo** [comment]
Yeah, it should be possible. You should first try locally before deploying to production to make sure that there isn't anything in this Docker image that is not compatible with your current setup. But it should probably "just work".
