### ISSUE TITLE
entrypoint.sh script in debug mode

### ISSUE THREAD

**Issue by olmax99** [tiangolo/meinheld-gunicorn-docker#2]
thanks for the nice work!
issue when running in sleep mode: 
        "   Attaching to dockerflask_web_1 
            web_1  | /entrypoint.sh: 22: [: bash: unexpected operator   "

Would that be a better way to check for arguments?
22 if [ $# -eq 0 ]; then
23    gunicorn -k egg:meinheld#gunicorn_worker -c "$GUNICORN_CONF" "$APP_MODULE"

**Comment by tiangolo** [comment]
Hey @olmax99 , sorry for the delay.

What do you mean with sleep mode?

**Comment by olmax99** [comment]
No problem, I am also just coming back for using your great builds again. Thanks for that.
When developing I've followed the bellow practice of launching the docker with the following command:

```
# Infinite loop, to keep it alive, for debugging
command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
```

Further, I would then launch the actual flask application:

`docker-compose exec web sh -c 'pipenv run flask run --host=0.0.0.0 --port=5000'`


This is what I was calling "sleep mode", and that is where the above mentioned "warnings" appeared.

**Comment by tiangolo** [comment]
Hey @olmax99 , thanks for your patience with this.

I think this was updated at some point after you started using the image to allow overriding the command entirely. I think should solve the problem...
