### ISSUE TITLE
Performance issues: 200% CPU

### ISSUE THREAD

**Issue by SpyRefused** [tiangolo/meinheld-gunicorn-docker#4]
Hi!

first of all, congratulate you on your work, you have some great tools here and I always use them.

Due to a problem with parallel processing with uwsgi, I have passed my Flask app from that image of uwsgi+nginx etc.. to this one of meinhled+gunicorn. Everything seems to go right, even the multiprocessing that didn't go well with uwsgi. But as soon as I start the container, the use of CPU is close to 100%, and as soon as I make a request, it reaches 200%... (this looking at it with "docker stats").

Any idea what might be happening? Thank you very much.

Regards.

**Comment by tiangolo** [comment]
> first of all, congratulate you on your work, you have some great tools here and I always use them.

Thanks! I'm glad it's being useful.

---

Have you checked running the base image alone? I mean, before adding your code. That way, we could know if it's related to the code in this image and how it is interacting with Docker, etc, or if it's related to something that could be happening in your app code.

---

Also, by default, this image has an "autotuning" mechanism, that is optimized for performance, starting 2 workers per CPU core. But it might be too much for your use case. You can configure/fine-tune it with environment variables: https://github.com/tiangolo/meinheld-gunicorn-docker#workers_per_core

**Comment by SpyRefused** [comment]
Finally the problem was due to SQLAlchemy-Flask, for some reason the SQLite file of the previous image left the processes stuck for some reason... I just had to load the file and generate the DB again from scratch and everything seems to be going correctly now.

Thank you very much for your help.

Best regards.

**Comment by tiangolo** [comment]
Great! I'm glad you solved it. Thanks for reporting back.
