### ISSUE TITLE
python 3.5 support

### ISSUE THREAD

**Issue by Rellim7** [tiangolo/meinheld-gunicorn-docker#7]
Hey thanks so much for making this!   Is there a way we could get a python 3.5 version as well?

**Comment by miguelgf** [comment]
Hello @Rellim7 

I guess the maintainer of this repo would be glad to receive a Pull request with this change, adding the 3.5 support.

You may take the steps he has done here https://github.com/tiangolo/meinheld-gunicorn-docker/pull/6 to copy the same structure and files to add 3.5 support.

A pull request will be more than welcome.
Regards

**Comment by tiangolo** [comment]
Thanks for the discussion here!

I would prefer to keep versions 3.6 and above to reduce the complexity of maintaining it. Is there any reason why would would *not* want to use Python 3.6 @Rellim7 ?
